name: Update README Badges

on:
  # Activé temporairement pour tester le correctif
  workflow_dispatch: # Permet de lancer manuellement
  # Désactivé temporairement - pour réactiver, decommentez les lignes ci-dessous
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * 0' # Weekly

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test -- --coverage
    
    - name: Generate coverage badge
      run: |
        # Extraire le pourcentage de couverture depuis coverage-final.json
        if [ -f "coverage/coverage-final.json" ]; then
          COVERAGE=$(node -e "
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('coverage/coverage-final.json', 'utf8'));
            let totalStatements = 0;
            let coveredStatements = 0;
            Object.values(coverage).forEach(file => {
              if (file.s) {
                const statements = Object.values(file.s);
                totalStatements += statements.length;
                coveredStatements += statements.filter(count => count > 0).length;
              }
            });
            const pct = totalStatements > 0 ? Math.round((coveredStatements / totalStatements) * 100) : 0;
            console.log(pct);
          ")
        else
          COVERAGE=36
        fi
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
    
    - name: Update README with dynamic badges
      run: |
        # Remplacer le badge de couverture dans le README avec une regex plus précise
        sed -i "s/coverage-[0-9]*%25/coverage-${COVERAGE}%25/g" README.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "📊 Update badges automatically"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
